image: gradle:alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build

build:
  stage: build
  script: gradle build
  after_script:
    - mv build/libs/*jar *jar
  artifacts:
    paths:
      - ./*.jar
