/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    application
}

repositories {
    mavenCentral()
    maven {
        url = uri("https://jitpack.io")
    }
}

dependencies {
    implementation(libs.com.github.dv8fromtheworld.jda)
    implementation(libs.com.google.code.gson.gson)
    implementation(libs.dev.arbjerg.lavaplayer)
    implementation(libs.org.slf4j.slf4j.reload4j)
    implementation(libs.se.michaelthelin.spotify.spotify.web.api.java)
    implementation(libs.xyz.gianlu.librespot.librespot.lib)
    implementation(libs.xyz.gianlu.librespot.librespot.player)
    testImplementation(libs.org.assertj.assertj.core)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.api)
    compileOnly("com.google.code.findbugs:jsr305:3.0.2")
}

group = "percyjw"
version = "0.9"
description = "Epic-Sounds-2-Project"
java.sourceCompatibility = JavaVersion.VERSION_17

application {
    mainClass.set("epicsounds2.main.Main")
}
